### ISSUE TITLE
curl requests generated in life version point to dev. endpoint

### ISSUE THREAD

**Issue by fsasaki** [freme-project/freme-project.github.io#172]
See this example
curl -X POST --header "Content-Type: text/plain" --header "Accept: text/n3" -d "I went to Prague." "http://api-dev.freme-project.eu/current/e-translation/tilde?informat=text&outformat=turtle&source-lang=en&target-lang=de&system=smt-0eba8517-0cf8-43b9-8dc2-ed99b33e56b9
generated via the form for e-Translation.

**Comment by jnehring** [comment]
I cannot reproduce this. Maybe it is solved when you refresh the page? This issue occured short time today morning and I have fixed it.

**Comment by fsasaki** [comment]
I still get the error. I write the request via this URL
http://api.freme-project.eu/doc/0.5/api-doc/simple.html#!/e-Entity/execute_0
and I get this request URL generated
http://api-dev.freme-project.eu/current/e-entity/freme-ner/documents?input=Al%20Pachino&informat=text&outformat=turtle&language=en&dataset=dbpedia&mode=link

**Comment by jnehring** [comment]
Thats odd. I still cannot see it. Lets take a look at this bug together next week.

**Comment by jnehring** [comment]
This is fixed
